// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuKZrGKxYAFZj3xP27wlCo_jHREqWSaWk',
    appId: '1:729785621076:web:41cbe5f37f7c53214b2bc1',
    messagingSenderId: '729785621076',
    projectId: 'app01iti',
    authDomain: 'app01iti.firebaseapp.com',
    storageBucket: 'app01iti.appspot.com',
    measurementId: 'G-S6P1W415HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AX-LJbXA2GwoN4DMQkfzncqMOahUWbA',
    appId: '1:729785621076:android:22041b8fd41ffce94b2bc1',
    messagingSenderId: '729785621076',
    projectId: 'app01iti',
    storageBucket: 'app01iti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00SbF0gIVyt5l5BSm5O4ytRvp17eQZqk',
    appId: '1:729785621076:ios:73a9669dc2b6463e4b2bc1',
    messagingSenderId: '729785621076',
    projectId: 'app01iti',
    storageBucket: 'app01iti.appspot.com',
    iosClientId: '729785621076-3qsujaal5bitr3jd8dqkvfjkhka3e8vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app01iti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD00SbF0gIVyt5l5BSm5O4ytRvp17eQZqk',
    appId: '1:729785621076:ios:73a9669dc2b6463e4b2bc1',
    messagingSenderId: '729785621076',
    projectId: 'app01iti',
    storageBucket: 'app01iti.appspot.com',
    iosClientId: '729785621076-3qsujaal5bitr3jd8dqkvfjkhka3e8vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app01iti',
  );
}
